### ISSUE TITLE
About the impact of the quality of C2L  

### ISSUE THREAD

**Issue by Junx0924** [youquanl/Segment-Any-Point-Cloud#4]
Hi, thanks for this fantastic project.

C2L refers to Camera-to-LiDAR distillation in Table.5 of the paper.

Is there any ablation study on the impact of the quality of C2L on performance?
As we know, the superpoints are generated by C2L from superpixels.
If there are larger time offset between lidar and camera data, there would be very few superpoints left due to mismatching.
eg (the pink color are projected lidar points):
![Screenshot from 2023-07-24 13-57-14](https://github.com/youquanl/Segment-Any-Point-Cloud/assets/18465543/2667d287-ed1c-4564-aa45-0775802263fb)

Since it is common that 2d-to-3d correspondence can be really bad in reality,  it would be great if this project can overcome this issue.

**Comment by ldkong1205** [comment]
Hi @Junx0924, thanks for your interest in this work!

Your mentioned concern about the quality of the 2D-3D correspondence is reasonable. We also observed similar patterns, *i.e.*, the misalignment between LiDAR and camera data. For your question:
- We didn't conduct an ablation experiment on the impact of different qualities in C2L, but rather consider the correspondence is accurate when mapping the 2D semantic superpixels to 3D semantic superpoints.
- We did attempt to tackle this problem; we proposed a temporal consistency regularization on the LiDAR data only to mitigate the negative impact of potential low-quality 2D-3D correspondence. 
- As suggested, we will further investigate this issue with more experiments and let you once we obtain something interesting on this. Thanks for your advice!

**Comment by Junx0924** [comment]
Hi @ldkong1205 , thanks very much for your quick and elaborate response.

I am looking forward to further experiments on the quality of C2L。

Because it is really very costly to get good 2D-3D correspondence during data collection trips.
Each camera requires intrinsic and extrinsic calibration (bad space alignment), also the camera poses at each timestamp.
there are six cameras in total, and the lidar and camera sensors often have different scan frequencies (bad time alignment).

These 2D-3D misalignments make it hard to reproduce the performance on custom datasets.

**Comment by ldkong1205** [comment]
Hi @Junx0924, thanks! We will keep you updated ~
