### ISSUE TITLE
Can you sharing the visualization code?

### ISSUE THREAD

**Issue by rockywind** [youquanl/Segment-Any-Point-Cloud#6]

**Comment by ldkong1205** [comment]
Hi @rockywind, thanks for your interest in this work!

Which visualization are you specifically looking for?

**Comment by rockywind** [comment]
您好，像类似这种可视化代码可以分享一下吗？
![image](https://github.com/youquanl/Segment-Any-Point-Cloud/assets/14838781/0f9367c1-492f-47da-b159-c0c0d9603a3c)

**Comment by ldkong1205** [comment]
@rockywind, 好的，代码将于近期上传

**Comment by rockywind** [comment]
十分感谢

**Comment by ldkong1205** [comment]
Hi @rockywind, 可视化代码已上传至: https://github.com/youquanl/Segment-Any-Point-Cloud/tree/main/visualization

如有其他疑问，可以新开一个issue ~
